language: node_js
node_js:
  - 12.0
cache:
    directories:
        - ./target
        - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf ./target/wasm32-unknown-unknown
  - rm -rf ./target/release
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup target add wasm32-unknown-unknown
  - npm i -g truffle
before_script:
  - cd src/tests && ./build.sh && cd ../..
script:
  - cargo test --lib
